setbounds(-5, -5, -5, 5, 5, 5)
inner = sphere(0, 0, 0, 3)
outer = offset(inner, 0.2)
shell = bsubtract(outer, inner)
cut = cylinder(-4, 0, 4, 4, 0, 4, 3.75)
cut = bunion(cut, cylinder(-4, 0, -4, 4, 0, -4, 3.75))
ring = bsubtract(shell, cut)
fill = bsubtract(inner, cut)
lat = bintersect(fill, gyroid(12, .2))
part = bunion(lat, ring)